# -*- coding: utf-8 -*-
#Author: Vodohleb04

# Form implementation generated from reading ui file 'helpDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import configs


class Ui_InfoDialog(object):
    def setupUi(self, InfoDialog):
        InfoDialog.setObjectName("InfoDialog")
        InfoDialog.resize(720, 406)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(configs.SERVICE_ICONS["gui_windows_icon"]), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        InfoDialog.setWindowIcon(icon)
        InfoDialog.setStyleSheet("background-color: rgb(255, 242, 254);")
        self.gridLayout_2 = QtWidgets.QGridLayout(InfoDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabsWidget = QtWidgets.QTabWidget(InfoDialog)
        self.tabsWidget.setObjectName("tabsWidget")
        self.generalTab = QtWidgets.QWidget()
        self.generalTab.setObjectName("generalTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.generalTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.generalInfo = QtWidgets.QTextEdit(self.generalTab)
        self.generalInfo.setStyleSheet("background-color: rgb(247, 255, 238);")
        self.generalInfo.setReadOnly(True)
        self.generalInfo.setObjectName("generalInfo")
        self.gridLayout_3.addWidget(self.generalInfo, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabsWidget.addTab(self.generalTab, "")
        self.blueberryTab = QtWidgets.QWidget()
        self.blueberryTab.setObjectName("blueberryTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.blueberryTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.blueBerryText = QtWidgets.QTextEdit(self.blueberryTab)
        self.blueBerryText.setStyleSheet("background-color: rgb(247, 255, 238);")
        self.blueBerryText.setReadOnly(True)
        self.blueBerryText.setObjectName("blueBerryText")
        self.gridLayout_5.addWidget(self.blueBerryText, 0, 1, 1, 1)
        self.blueberryIcon = QtWidgets.QLabel(self.blueberryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blueberryIcon.sizePolicy().hasHeightForWidth())
        self.blueberryIcon.setSizePolicy(sizePolicy)
        self.blueberryIcon.setMinimumSize(QtCore.QSize(300, 300))
        self.blueberryIcon.setMaximumSize(QtCore.QSize(300, 300))
        self.blueberryIcon.setText("")
        self.blueberryIcon.setPixmap(QtGui.QPixmap(configs.FUNNY_FACTS_PICTURES["blueberry_picture"]))
        self.blueberryIcon.setScaledContents(True)
        self.blueberryIcon.setObjectName("blueberryIcon")
        self.gridLayout_5.addWidget(self.blueberryIcon, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabsWidget.addTab(self.blueberryTab, "")
        self.hazelTab = QtWidgets.QWidget()
        self.hazelTab.setObjectName("hazelTab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.hazelTab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.hazelIcon = QtWidgets.QLabel(self.hazelTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hazelIcon.sizePolicy().hasHeightForWidth())
        self.hazelIcon.setSizePolicy(sizePolicy)
        self.hazelIcon.setMinimumSize(QtCore.QSize(422, 230))
        self.hazelIcon.setMaximumSize(QtCore.QSize(422, 230))
        self.hazelIcon.setAutoFillBackground(False)
        self.hazelIcon.setText("")
        self.hazelIcon.setPixmap(QtGui.QPixmap(configs.FUNNY_FACTS_PICTURES["hazel_picture"]))
        self.hazelIcon.setObjectName("hazelIcon")
        self.gridLayout_7.addWidget(self.hazelIcon, 0, 0, 1, 1)
        self.hazelInfo = QtWidgets.QTextEdit(self.hazelTab)
        self.hazelInfo.setStyleSheet("background-color: rgb(247, 255, 238);")
        self.hazelInfo.setReadOnly(True)
        self.hazelInfo.setObjectName("hazelInfo")
        self.gridLayout_7.addWidget(self.hazelInfo, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tabsWidget.addTab(self.hazelTab, "")
        self.mapleTab = QtWidgets.QWidget()
        self.mapleTab.setObjectName("mapleTab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.mapleTab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.mapleIcon = QtWidgets.QLabel(self.mapleTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapleIcon.sizePolicy().hasHeightForWidth())
        self.mapleIcon.setSizePolicy(sizePolicy)
        self.mapleIcon.setMinimumSize(QtCore.QSize(447, 250))
        self.mapleIcon.setMaximumSize(QtCore.QSize(447, 250))
        self.mapleIcon.setText("")
        self.mapleIcon.setPixmap(QtGui.QPixmap(configs.FUNNY_FACTS_PICTURES["maple_picture"]))
        self.mapleIcon.setObjectName("mapleIcon")
        self.gridLayout_9.addWidget(self.mapleIcon, 0, 0, 1, 1)
        self.mapleInfo_2 = QtWidgets.QTextEdit(self.mapleTab)
        self.mapleInfo_2.setStyleSheet("background-color: rgb(247, 255, 238);")
        self.mapleInfo_2.setReadOnly(True)
        self.mapleInfo_2.setObjectName("mapleInfo_2")
        self.gridLayout_9.addWidget(self.mapleInfo_2, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.tabsWidget.addTab(self.mapleTab, "")
        self.boarTab = QtWidgets.QWidget()
        self.boarTab.setObjectName("boarTab")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.boarTab)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.boarIcon = QtWidgets.QLabel(self.boarTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boarIcon.sizePolicy().hasHeightForWidth())
        self.boarIcon.setSizePolicy(sizePolicy)
        self.boarIcon.setMinimumSize(QtCore.QSize(300, 300))
        self.boarIcon.setMaximumSize(QtCore.QSize(300, 300))
        self.boarIcon.setText("")
        self.boarIcon.setPixmap(QtGui.QPixmap(configs.FUNNY_FACTS_PICTURES["boar_picture"]))
        self.boarIcon.setObjectName("boarIcon")
        self.gridLayout_11.addWidget(self.boarIcon, 0, 0, 1, 1)
        self.boarInfo = QtWidgets.QTextEdit(self.boarTab)
        self.boarInfo.setStyleSheet("background-color: rgb(247, 255, 238);")
        self.boarInfo.setReadOnly(True)
        self.boarInfo.setObjectName("boarInfo")
        self.gridLayout_11.addWidget(self.boarInfo, 0, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.tabsWidget.addTab(self.boarTab, "")
        self.elkTab = QtWidgets.QWidget()
        self.elkTab.setObjectName("elkTab")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.elkTab)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.elkIcon = QtWidgets.QLabel(self.elkTab)
        self.elkIcon.setMinimumSize(QtCore.QSize(300, 250))
        self.elkIcon.setMaximumSize(QtCore.QSize(300, 250))
        self.elkIcon.setText("")
        self.elkIcon.setPixmap(QtGui.QPixmap(configs.FUNNY_FACTS_PICTURES["elk_picture"]))
        self.elkIcon.setObjectName("elkIcon")
        self.gridLayout_14.addWidget(self.elkIcon, 0, 0, 1, 1)
        self.elkInfo = QtWidgets.QTextEdit(self.elkTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elkInfo.sizePolicy().hasHeightForWidth())
        self.elkInfo.setSizePolicy(sizePolicy)
        self.elkInfo.setStyleSheet("background-color: rgb(247, 255, 238);")
        self.elkInfo.setReadOnly(True)
        self.elkInfo.setObjectName("elkInfo")
        self.gridLayout_14.addWidget(self.elkInfo, 0, 1, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.tabsWidget.addTab(self.elkTab, "")
        self.wolfTab = QtWidgets.QWidget()
        self.wolfTab.setObjectName("wolfTab")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.wolfTab)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.wolfIcon = QtWidgets.QLabel(self.wolfTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wolfIcon.sizePolicy().hasHeightForWidth())
        self.wolfIcon.setSizePolicy(sizePolicy)
        self.wolfIcon.setMinimumSize(QtCore.QSize(360, 242))
        self.wolfIcon.setMaximumSize(QtCore.QSize(360, 242))
        self.wolfIcon.setText("")
        self.wolfIcon.setPixmap(QtGui.QPixmap(configs.FUNNY_FACTS_PICTURES["wolf_picture"]))
        self.wolfIcon.setObjectName("wolfIcon")
        self.gridLayout_16.addWidget(self.wolfIcon, 0, 0, 1, 1)
        self.wolfInfo = QtWidgets.QTextEdit(self.wolfTab)
        self.wolfInfo.setStyleSheet("background-color: rgb(247, 255, 238);")
        self.wolfInfo.setObjectName("wolfInfo")
        self.gridLayout_16.addWidget(self.wolfInfo, 0, 1, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.tabsWidget.addTab(self.wolfTab, "")
        self.bearTab = QtWidgets.QWidget()
        self.bearTab.setObjectName("bearTab")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.bearTab)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.bearIcon = QtWidgets.QLabel(self.bearTab)
        self.bearIcon.setMinimumSize(QtCore.QSize(300, 300))
        self.bearIcon.setMaximumSize(QtCore.QSize(300, 300))
        self.bearIcon.setText("")
        self.bearIcon.setPixmap(QtGui.QPixmap(configs.FUNNY_FACTS_PICTURES["bear_picture"]))
        self.bearIcon.setObjectName("bearIcon")
        self.gridLayout_18.addWidget(self.bearIcon, 0, 0, 1, 1)
        self.bearInfo2 = QtWidgets.QTextEdit(self.bearTab)
        self.bearInfo2.setStyleSheet("background-color: rgb(247, 255, 238);")
        self.bearInfo2.setReadOnly(True)
        self.bearInfo2.setObjectName("bearInfo2")
        self.gridLayout_18.addWidget(self.bearInfo2, 0, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.tabsWidget.addTab(self.bearTab, "")
        self.otherTab = QtWidgets.QWidget()
        self.otherTab.setObjectName("otherTab")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.otherTab)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.otherInfo = QtWidgets.QTextEdit(self.otherTab)
        self.otherInfo.setStyleSheet("background-color: rgb(247, 255, 238);")
        self.otherInfo.setReadOnly(True)
        self.otherInfo.setObjectName("otherInfo")
        self.gridLayout_20.addWidget(self.otherInfo, 0, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_20, 0, 0, 1, 1)
        self.tabsWidget.addTab(self.otherTab, "")
        self.gridLayout.addWidget(self.tabsWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(InfoDialog)
        self.buttonBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.buttonBox.setStyleSheet("background-color: rgb(224, 224, 255);")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(InfoDialog)
        self.tabsWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(InfoDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(InfoDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(InfoDialog)

    def retranslateUi(self, InfoDialog):
        _translate = QtCore.QCoreApplication.translate
        InfoDialog.setWindowTitle(_translate("InfoDialog", "Помощь"))
        self.generalInfo.setHtml(_translate("InfoDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Forest Simulation - version {configs.VERSION} release (04.05.2023)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Автор: Vodohleb04 (Yackubovskiy Kirill, 121703)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  ППОИС, лаб.4</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">There are 7 types of creatures that can be a part of ecosystem:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Plants are:    - Blueberry    - Hazel    - Maple</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Animals are    :    - Boar(Herbivore animal)    - Elk(Herbivore animal)     - Wolf(Predator animal)    - Bear(Omnivorous)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> Every creature dies after some period. Deadly worm - immortal forest entity that destroy died animals.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> Deadly worm sleeps for some period that is named deadly worm sleep interval.</p></body></html>"))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.generalTab), _translate("InfoDialog", "Общая информация"))
        self.blueBerryText.setHtml(_translate("InfoDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Blueberry:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Средняя продолжительность жизни: 3 периода</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Разброс ростков: 1 гектар</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Количество ростков: 2-4</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Скорость регенерации: 5/период</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Изначальная сила: 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Коэффициент роста силы: 0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Личный коэффициент силы: 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Пищевая ценность плода: 5 ккал</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Количество плодов: 10-15</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Здоровье: 10</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Репродуктивный возраст: 1-4 периоды жизни</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Стерильный период: 0 периодов</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Именно этот сорт черники использовали как прототип вспоминики из мультсериала South Park</p></body></html>"))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.blueberryTab), _translate("InfoDialog", configs.RussianCreaturesNames.BLUEBERRY.value))
        self.hazelInfo.setHtml(_translate("InfoDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> Hazel:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Средняя продолжительность жизни: 70 периодов</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Разброс ростков: 1 гектар</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Количество ростков:2-4</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Скорость регенерации: 13/период</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Изначальная сила: 5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Коэффициент роста силы: 2/3</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Личный коэффициент силы: 20/25 -&gt; 30/25</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Пищевая ценность плода: 10 ккал</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Количество плодов: 10-15</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Здоровье: 400</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Репродуктивный возраст: 30-70 периоды жизни</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Стерильный период: 0 периодов</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Характер: твёрдый</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Не женат</p></body></html>"))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.hazelTab), _translate("InfoDialog", configs.RussianCreaturesNames.HAZEL.value))
        self.mapleInfo_2.setHtml(_translate("InfoDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Maple:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Средняя продолжительность жизни: 200 периодов</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Разброс ростков: 2 гектара</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Количество ростков:1-3</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Скорость регенерации:50/период</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Изначальная сила: 10</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Коэффициент роста силы: 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Личный коэффициент силы: 40/50 -&gt; 55/50</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Пищевая ценность плода: 5 ккал</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Количество плодов: 25-35</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Здоровье: 1000</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Репродуктивный возраст: 50-200 периоды жизни</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Стерильный период: 0 периодов</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Никогда не спрашивайте в Канаде, кто такой клён...</p></body></html>"))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.mapleTab), _translate("InfoDialog", configs.RussianCreaturesNames.MAPLE.value))
        self.boarInfo.setHtml(_translate("InfoDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Boar:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Средняя продолжительность жизни: 15 периодов</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Количество детёнышей: 3-5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Изначальная сила:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Женская особь: 8</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Мужская особь: 10</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Коэффициент роста силы:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Женская особь: 24/5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Мужская особь: 6</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Личный коэффициент силы:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Женская особь: 25/30 -&gt; 35/30</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Мужская особь: 35/40 -&gt; 45/40</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Пищевая ценность: 250 ккал</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Здоровье: 200</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Наносимый урон: 100</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Репродуктивный возраст: 5-11 периоды жизни</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Требуемое количество растительной пищи: 100 ккал</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Скорость голодания: 75 ккал/период</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Стерильный период: 2 периода</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">На фото экспериментальный образей данного типа.</p></body></html>"))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.boarTab), _translate("InfoDialog", configs.RussianCreaturesNames.BOAR.value))
        self.elkInfo.setHtml(_translate("InfoDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Elk:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Средняя продолжительность жизни: 14 периодов</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Количество детёнышей: 2-3</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Изначальная сила:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Женская особь: 10</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Мужская особь: 15</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Коэффициент роста силы:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Женская особь: 42.5/4</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Мужская особь: 12.5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Личный коэффициент силы:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Женская особь: 40/52.5 -&gt; 65/52.5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Мужская особь: 55/65 - &gt; 75/65</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Пищевая ценность: 600 ккал</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Здоровье: 350</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Наносимый урон: 300</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Репродуктивный возраст: 4-12 периоды жизни</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Требуемое количество растительной пищи: 125 ккал</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Скорость голодания: 100 ккал/период</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Стерильный период: 3 периода</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Это феноменально...</p></body></html>"))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.elkTab), _translate("InfoDialog", configs.RussianCreaturesNames.ELK.value))
        self.wolfInfo.setHtml(_translate("InfoDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Wolf:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Средняя продолжительность жизни: 10 периодов</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Количество детёнышей: 3-5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Изначальная сила:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Женская особь: 10</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Мужская особь: 12</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Коэффициент роста силы:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Женская особь: 35/3</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Мужская особь: 40.5/3</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Личный коэффициент силы:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Женская особь: 35/45 -&gt; 55/45</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Мужская особь: 40/52.5 -&gt; 65/52.5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Пищевая ценность: 200 ккал</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Здоровье: 200</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Наносимый урон: 200</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Репродуктивный возраст: 3-9 периоды жизни</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Требуемое количество растительной пищи: 0 ккал</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Скорость голодания: 100 ккал/период</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Стерильный период: 2 периода</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Думает, что очень умный и мудрый</p></body></html>"))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.wolfTab), _translate("InfoDialog", configs.RussianCreaturesNames.WOLF.value))
        self.bearInfo2.setHtml(_translate("InfoDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Bear:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Средняя продолжительность жизни: 25 периодов</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Количество детёнышей: 2-3</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Изначальная сила:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Женская особь: 12</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Мужская особь: 15</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Коэффициент роста силы:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Женская особь: 55.5/8</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Мужская особь: 55/8</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Личный коэффициент силы:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Женская особь: 55/67.5 -&gt; 80/67.5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                Мужская особь: 60/70 -&gt; 80/70</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Пищевая ценность: 600 ккал</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Здоровье: 300</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Наносимый урон: 350</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Репродуктивный возраст: 8-20 периоды жизни</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Требуемое количество растительной пищи: 150 ккал</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Скорость голодания: 150 ккал/период</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            Стерильный период: 4 периода</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            3/4 рациона составляет растительная пища</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Сбежал из психбольницы</p></body></html>"))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.bearTab), _translate("InfoDialog", configs.RussianCreaturesNames.BEAR.value))
        self.otherInfo.setHtml(_translate("InfoDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Все животные после определённого периода времени или по иным причинам умирают. Их тела храняться в течении периода</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  времени. После чего их уничтожает смерто-червь - бессмертное существо, очищающее экосистему.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Базовые значения для экосистемы (автозаполнение исполльзует именно эти значения):</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Вертикальные размеры поля: 7 (0 -&gt; 6)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Горизонтальные размеры поля: 7 (0 -&gt; 6)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Время бездействия смерто-червя: 5 периодов</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Значения количества существ в зависимости от типа:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        blueberry: 20</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        hazel: 10</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        maple: 10</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        boar: 12</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        elk: 6</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        wolf: 12</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        bear: 6</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  В экосистеме единицей времени является период. За каждый период происходит следующая последовательность событий:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  1. Животные ищут пищу</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  2. Растения и животные размножаются (если в данный период они способны это сделать)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  3. Животные передвигаются в другой гектар</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  После любого периода с определённой вероятностью каждое существо может погибнуть (внезапная смерть), а так же может</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  произойти апокалипсис, после чего все существа погибнут. Размножение и передвижение происходит с определённой</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  вероятностью, следовательно, не все способные передвигаться и размножаться существа по истечении периода сделают это.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.otherTab), _translate("InfoDialog", "Прочее"))



